"""Set 053 S1 cross-provider consensus. Deleted after run (artifacts saved).
Two providers (gemini-pro=google, gpt-5-4=openai) each evaluate AND
adversarially attack the proposal's load-bearing dispositions. call_model
gets the PROVIDER-SCOPED config; gpt-5-4 falls back to gpt-5-4-mini on error."""
import json
from ai_router.config import load_config
from ai_router import providers

cfg = load_config()

SYSTEM = (
    "You are an independent reviewer on a cross-provider design panel. You did "
    "NOT write this proposal. Evaluate it, then ADVERSARIALLY attack its "
    "load-bearing choices -- do not just agree. Respond ONLY as JSON with keys: "
    "per_disposition (object mapping Q-id -> {'verdict':'agree'|'disagree'|'modify', "
    "'why': short string}), baseline_allowlist_verdict (string -- is the committed "
    "baseline-allowlist the right way to enforce NEW drift without git-diff or a "
    "forced sweep, or worse than the alternatives? be specific), centerpiece_verdict "
    "(string -- is CI the right centerpiece given writers already stamp from the "
    "constant?), strongest_objection (string), missing (list of strings)."
)

USER = r"""
Review this proposal for an AI-led-workflow tooling change. Background: state
files (docs/session-sets/<slug>/session-state.json) carry a numeric
"schemaVersion" (current=4). Failure mode: an AI orchestrator or human
HAND-AUTHORS a file with a stale schemaVersion, silently regressing it (happened
once). Detection already exists (`check_migrations` CLI, exits non-zero on
drift). The gap: the only AUTOMATIC trigger is a Claude Code SessionStart hook,
but most staff use GITHUB COPILOT (no executable session-start hook) and repos
may be on AZURE DEVOPS not GitHub. So enforcement must be CI/host/AI-agnostic.

EMPIRICAL INVENTORY (just done, trust it):
- EVERY code writer (Python + TS) ALREADY stamps schemaVersion from a shared
  constant; none use literals or pass-through. So "writer-path hardening" is
  already satisfied -- it cannot be the strategic core, and it cannot catch a
  HAND-EDIT (which bypasses all writers -- the actual failure vector).
- check_migrations scans the repo-wide set list; it has NO git/changed-files
  awareness today.
- AGENTS.md content is generated by ai_router/narration.py _AGENTS_TEMPLATE.
- The reader shim fails loud on structural breaks but does NOT validate that
  content matches the declared schemaVersion number.

RECOMMENDED DISPOSITIONS:
- Q1/Q8 CENTERPIECE: CI gate is the centerpiece (only source-agnostic,
  non-bypassable catch -- sees hand-edits). Layers in priority: (1) CI
  required-check, (2) git pre-commit + pre-push hook, (3) AGENTS.md/copilot
  advisory, (4) writer-convention TEST pinning the already-done hardening.
- Q2 HOOKS: committed core.hooksPath dir + one-line enable; accept --no-verify
  is bypassable (that's why CI is mandatory); add pre-push for bot/tooling.
- Q3 CI PACKAGING: one cross-platform wrapper script the CI invokes + thin
  committed Azure Pipelines & GitHub Actions templates + generic recipe.
- Q4 WRITER AUDIT: CLOSED by inventory; shrinks to a convention test.
- Q5 ADVISORY: add a line to narration.py _AGENTS_TEMPLATE/_CLAUDE_TEMPLATE AND
  close the distribution gap (write repo-root AGENTS.md + .github/copilot-
  instructions.md, not just per-set artifacts). Weakest layer.
- Q6 REQUIRED-FOR-MERGE: document the manual Azure Branch-Policy build-
  validation == GitHub required-status-check enablement.
- Q7 SCAN SCOPE (LOAD-BEARING): repo-wide scan but fail only on NEW drift via a
  committed BASELINE ALLOWLIST (schema-drift-baseline.json listing sets
  intentionally left old). CI fails if a set is sub-current AND not in the
  baseline. Sidesteps brittle git-diff entirely AND honors the operator-locked
  "old schema is acceptable" non-goal. A new sub-current write isn't in the
  baseline -> fails.
- Q9 FIXER: add `check_migrations --fix` running the existing migrator chain
  (.bak-backed); operator-invoked/reversible, so NOT "silent auto-migration".
- Q10 CONTENT VALIDATION: optional `--validate-content` checks JSON conforms to
  its declared schemaVersion, not just the number.
- Q11 KEEP the "old schema acceptable" non-goal (baseline gives new-drift
  enforcement without a forced sweep).
- Q12 ESCAPE HATCH = baseline membership (explicit, reviewed opt-out).
- Q13 AZURE: explicit python-setup + pip install on agent; ##vso[task.logissue
  type=error] PR-surface errors; document manual build-validation policy step;
  no target-branch diff needed (baseline makes the check branch-independent).

THE KEY TENSION: Is the committed BASELINE ALLOWLIST (Q7/Q11/Q12) the right
mechanism, or is its maintenance burden (every intentionally-old set must be
listed, and the file itself can rot) worse than (a) git-diff changed-files or
(b) a one-time forced migration sweep that eliminates old schemas entirely?
Attack this. Also: is CI truly the right centerpiece, or is there a better
non-bypassable point? JSON only.
"""


def call(engine, provider):
    mid = cfg["models"][engine]["model_id"]
    gp = {"thinking_budget": 4096} if provider == "google" else None
    res = providers.call_model(
        provider_name=provider, model_id=mid, system_prompt=SYSTEM,
        user_message=USER, max_tokens=16000,
        config=cfg["providers"][provider], generation_params=gp,
    )
    m = cfg["models"][engine]
    cost = (res.input_tokens / 1e6) * m["input_cost_per_1m"] + (
        res.output_tokens / 1e6) * m["output_cost_per_1m"]
    return res, round(cost, 4)


total = 0.0
for engine, provider in [("gemini-pro", "google"), ("gpt-5-4", "openai")]:
    try:
        res, cost = call(engine, provider)
    except Exception as e:
        print(f"\n### {engine} FAILED: {type(e).__name__}: {e}")
        if engine == "gpt-5-4":
            try:
                res, cost = call("gpt-5-4-mini", "openai")
                engine = "gpt-5-4-mini (fallback)"
            except Exception as e2:
                print(f"### fallback also failed: {e2}")
                continue
        else:
            continue
    total += cost
    print(f"\n{'='*70}\n### {engine} ({provider})  cost=${cost}  "
          f"in={res.input_tokens} out={res.output_tokens}\n{'='*70}")
    print(res.content)

print(f"\n\n### TOTAL CONSENSUS COST: ${round(total, 4)}")
